import asyncio
import json
import sys
from agent import app

async def run_enterprise_pipeline():
    print("🚀 Initializing L&D Curriculum Agent State Machine...", flush=True)
    
    config = {"configurable": {"thread_id": "cv-project-run-101"}}
    
    initial_state = {
        "target_role": "Junior Backend Developer to Production AWS Cloud Engineer",
        "competitor_url": "https://amazon.com",
        "iterations": 0
    }
    
    print("⚡ Invoking LangGraph workflow graph directly...", flush=True)
    
    try:
        # Using ainvoke directly avoids streaming buffer blocks on Windows
        final_state = await app.ainvoke(initial_state, config)
        output_data = final_state.get("final_output")
        
        print("\n🎯 ==================================================", flush=True)
        print("💎 FINAL STRUCTURED CURRICULUM OUTPUT (GENERATED BY AGENT):", flush=True)
        print("====================================================", flush=True)
        if output_data:
            print(json.dumps(output_data, indent=2), flush=True)
        else:
            print("❌ Pipeline finished, but no structured output was verified by the Reviewer node.", flush=True)
            
    except Exception as e:
        print(f"\n❌ Execution Error caught: {e}", file=sys.stderr, flush=True)

if __name__ == "__main__":
    asyncio.run(run_enterprise_pipeline())
